[phases.setup]
nixpkgs = ["python311", "gcc"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install -r requirements.txt"
]

[phases.start]
cmds = ["/opt/venv/bin/gunicorn main:app --bind 0.0.0.0:${PORT}"]
